### ISSUE TITLE
Installation failures! Oh no!

### ISSUE THREAD

**Issue by kidfribble** [DjebbZ/revealjs-docpad#2]
Any help is appreciated!

I'm getting the following errors on installation exclusively with revealjs skeleton:

```
error: An error occured: 
Error: Couldn't find the selector slideOrder
    at Query.compileSelector (/usr/local/lib/node_modules/docpad/node_modules/query-engine/out/lib/query-engine.js:1499:15)
    at Query.compileQuery (/usr/local/lib/node_modules/docpad/node_modules/query-engine/out/lib/query-engine.js:1604:37)
```

And a little later:

```
warning: Something went wrong while rendering: /Users/steventrevathan/Sites/typeplate_test/src/documents/index.html.coffee
error: Something went wrong with the action
error: An error occured: 
TypeError: Cannot call method 'toJSON' of undefined
    at Object.eval (eval at <anonymous> (/Users/steventrevathan/Sites/typeplate_test/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:410:10), <anonymous>:272:43)
    at Object.__cc.render_contents (eval at <anonymous> (/Users/steventrevathan/Sites/typeplate_test/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:410:10), <anonymous>:108:29)
```

**Comment by SteveMcArthur** [comment]
The problem  seems to be the call to <code>database.findAllLive</code> at the bottom of the docpad.coffee file. At the moment it reads:

<pre><code>database.findAllLive({tags: $has: 'slide', slideOrder: $exists: true},{slideOrder:1})</code></pre>

It should be (note the tags and slideOrder properties):

<pre><code>database.findAllLive({tags: {$has: 'slide'}, slideOrder: {$exists: true}},{slideOrder:1})</code></pre>

Also posted on the docpad issue #414 https://github.com/bevry/docpad/issues/414

**Comment by jedschneider** [comment]
why was this commit reverted. seems to be the solution for me to get this to run.

**Comment by SteveMcArthur** [comment]
Sorry - that was me having trouble with git

**Comment by holmboe** [comment]
This seems to be the case still in the master branch.

ping @SteveMcArthur @DjebbZ
