### ISSUE TITLE
Installation failure again...

### ISSUE THREAD

**Issue by ms440** [DjebbZ/revealjs-docpad#4]
**As recommended I've done**

```
git clone git://github.com/DjebbZ/revealjs-docpad.git
cd revealjs-docpad\
npm install
```

**I got**

```
 Error: Couldn't find the selector slideOrder
    at Query.compileSelector (E:\2013\Learning\docpad\Reveal\revealjs-docpad\node_modules\docpad\node_modules\query-engine\out\lib\query-engine.js:1499:15)
    at Query.compileQuery (E:\2013\Learning\docpad\Reveal\revealjs-docpad\node_modules\docpad\node_modules\query-engine\out\lib\query-engine.js:1604:37)
    at new Query (E:\2013\Learning\docpad\Reveal\revealjs-docpad\node_modules\docpad\node_modules\query-engine\out\lib\query-engine.js:1483:12)
    at FilesCollection.Criteria.setQuery (E:\2013\Learning\docpad\Reveal\revealjs-docpad\node_modules\docpad\node_modules\query-engine\out\lib\query-engine.js:854:19)
    at FilesCollection.Criteria.setQueries (E:\2013\Learning\docpad\Reveal\revealjs-docpad\node_modules\docpad\node_modules\query-engine\out\lib\query-engine.js:840:14)
    at FilesCollection.Criteria.applyCriteriaOptions (E:\2013\Learning\docpad\Reveal\revealjs-docpad\node_modules\docpad\node_modules\query-engine\out\lib\query-engine.js:749:16)
    at FilesCollection.QueryCollection.initialize (E:\2013\Learning\docpad\Reveal\revealjs-docpad\node_modules\docpad\node_modules\query-engine\out\lib\query-engine.js:331:14)
    at FilesCollection.initialize (E:\2013\Learning\docpad\Reveal\revealjs-docpad\node_modules\docpad\out\lib\collections\files.js:35:49)
    at FilesCollection.Backbone.Collection (E:\2013\Learning\docpad\Reveal\revealjs-docpad\node_modules\docpad\node_modules\backbone\backbone.js:603:21)
    at FilesCollection.QueryCollection (E:\2013\Learning\docpad\Reveal\revealjs-docpad\node_modules\docpad\node_modules\query-engine\out\lib\query-engine.js:307:107)
    at FilesCollection.QueryCollection (E:\2013\Learning\docpad\Reveal\revealjs-docpad\node_modules\docpad\out\lib\base.js:121:51)
    at new FilesCollection (E:\2013\Learning\docpad\Reveal\revealjs-docpad\node_modules\docpad\out\lib\collections\files.js:16:51)
    at FilesCollection.QueryCollection.createChildCollection (E:\2013\Learning\docpad\Reveal\revealjs-docpad\node_modules\docpad\node_modules\query-engine\out\lib\query-engine.js:365:22)
    at FilesCollection.QueryCollection.createLiveChildCollection (E:\2013\Learning\docpad\Reveal\revealjs-docpad\node_modules\docpad\node_modules\query-engine\out\lib\query-engine.js:374:27)
    at FilesCollection.QueryCollection.findAllLive (E:\2013\Learning\docpad\Reveal\revealjs-docpad\node_modulesdocpad\node_modules\query-engine\out\lib\query-engine.js:506:27)
    at DocPad.docpadConfig.collections.slides (E:\2013\Learning\docpad\Reveal\revealjs-docpad\docpad.coffee:28:25)
    at ambi (E:\2013\Learning\docpad\Reveal\revealjs-docpad\node_modules\docpad\node_modules\ambi\out\lib\ambi.js:24:25)
    at Task.method (E:\2013\Learning\docpad\Reveal\revealjs-docpad\node_modules\docpad\out\lib\docpad.js:1655:16)
    at ambi (E:\2013\Learning\docpad\Reveal\revealjs-docpad\node_modules\docpad\node_modules\ambi\out\lib\ambi.js:22:16)
    at E:\2013\Learning\docpad\Reveal\revealjs-docpad\node_modules\docpad\node_modules\taskgroup\out\lib\taskgroup.js:117:19
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at Task.fire (E:\2013\Learning\docpad\Reveal\revealjs-docpad\node_modules\docpad\node_modules\taskgroup\outlib\taskgroup.js:116:21)
    at process._tickDomainCallback (node.js:459:13)
An error occured within the child DocPad instance: exited with a non-zero status code
```

Looks very similar to the [closed] issue reported earlier...

**Comment by ifraixedes** [comment]
+1 with Docpad version 6.54.0
